### 개별 게시글 조회
GET http://localhost:3000/api/v1/posts/1

### 사용자 추가
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "email": "test1",
  "password": "test1pw",
  "nickname": "tester1"
}
